/*
* File:     randi.c
*
* Author:   Dr. Kerry Veenstra
*
* Purpose:  Generate a sequence of 1,000,000 pseudo-random numbers whose
*           values range between 0 and 999999.
*
*           We use this pseudo-random number generator for CSE 13S because
*           we want to be sure that all students' programs get the same
*           sequence of numbers.  Orinarily we would use random(), but we
*           know that random() can return a different sequence of numbers on
*           different systems.
*
* History:  A scaled version of this algorithm first was used in user
*           programs of early Hewlett-Packard programmable calculators.
*
*           The calculators used base-10 arithmetic (not binary).  They
*           could represent fractional values like 0.211327 exactly.
*
*           The calculator equation for computing the next pseudo-random
*           value of the sequence is below.  The frac() function zeroes
*           out the digits of the number to the left of the decimal point.
*
*               X_next = frac(9821 * X + 0.211327)
*
*           Scaling everything by 1000000 converts all values into
*           integers, and then the frac() function becomes the modulus
*           operator.
*
*               X_next = (9821 * X + 211327) % 1000000;
*
*           The value 9821 * X could be as large as 9821 * 999999 =
*           9,820,990,179, which is too large for a 32-bit variable, and so
*           we need to use a 64-bit variable.  (A 32-bit unsigned int can
*           store a value as large as 2^32 - 1 = 4,294,967,295.)
*
*           One can test this function by calling it 1000000 times and
*           then confirming that it generates 1000000 different values.
*/

/*
* DO NOT EDIT THIS FILE
*/

#include "randi.h"

#include <inttypes.h>

static uint64_t current_random = 0;

void randi_seed(unsigned seed) {
    current_random = (uint64_t) seed % 1000000;
}

int randi(void) {
    current_random = (9821 * current_random + 211327) % 1000000;
    return (int) current_random;
}
