/*
* File:     strings.h
* Purpose:  Provide strings for CSE 13S, Winter 2026, Assignment 3, LCR
*/

/*
* DO NOT EDIT THIS FILE
*/

/*
* Here are strings that you can use with printf().  Using them is optional.
*/
#define PROGRAM_USAGE_s       "Usage:  %s num_players seed\n"
#define ERROR_INVALID_PLAYERS "Invalid number of players. Using 3 instead.\n"
#define ERROR_INVALID_SEED    "Invalid seed. Using 4823 instead.\n"
#define CURRENT_SCORES        "Current scores:\n"
#define SCORE_ds              "    %d -- %s\n"
#define TURN_s                "%s's turn:\n"
#define ROLLS_c               "    Rolls %c\n"
#define GIVES_A_CHIP_TO_s     "        Gives a chip to %s\n"
#define PUTS_A_CHIP           "        Puts a chip in the pot\n"
#define HAS_NO_CHIPS_s        "%s has no chips, skipping turn\n"
#define ONE_PLAYER_HAS_CHIPS  "Now only one player has chips\n"
#define WON_s                 "%s won!\n"

/*
* The array player_name[] is defined in game.c, but we want to reference it
* in other .c files.  So include strings.h at the top of a .c file, and you
* can use player_name[] and MAX_PLAYERS in that file.
*/
extern const char *player_name[11];

/*
* How many players are listed in the array player_name?
*/
#define MAX_PLAYERS ((int) (sizeof(player_name) / sizeof(player_name[0])))
